apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: general
  name: integration-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: integration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: general
  name: integration
spec:
  replicas: 5
  selector:
    matchLabels:
      app: integration
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/skip-outbound-ports: 25061-25061
      namespace: general
      labels:
        app: integration
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: general
      containers:
        - name: integration
          image: registry.digitalocean.com/athenabot/integration-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: rediss://default:kulqkv6en3um9u09@private-athena-redis-do-user-9223163-0.b.db.ondigitalocean.com:25061
            - name: PG_URL
              value: postgresql://doadmin:rh3rc0vgg1f706kz@private-athenadb-do-user-9223163-0.b.db.ondigitalocean.com:25060/defaultdb
            #            - name: ENVIRONMENT
            #              value: Production
            - name: SAMPLE_RATE
              value: "1.0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DO_TOKEN
              value: e10b653ac96857bde053be5c9fefa2612d8ffb6df72702a0700b3c81dedabd53
