apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: general
  name: monitor-controller
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: monitor-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: general
  name: monitor-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-controller
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      namespace: general
      labels:
        app: monitor-controller
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: monitors
      containers:
        - name: monitor-controller
          image: registry.digitalocean.com/athenabot/monitors/controller:latest
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: rediss://default:n6luoc78ac44pgs0@test-redis-do-user-9223163-0.b.db.ondigitalocean.com:25061
            - name: PG_URL
              value: postgresql://doadmin:olwikzizq24jj9ni@test-pg-do-user-9223163-0.b.db.ondigitalocean.com:25060/defaultdb