apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: general
  name: statistics
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: grpc
  selector:
    app: statistics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: general
  name: statistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      namespace: general
      labels:
        app: statistics
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: general
      containers:
        - name: statistics
          image: registry.digitalocean.com/athenabot/statistics-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: rediss://default:kulqkv6en3um9u09@private-athena-redis-do-user-9223163-0.b.db.ondigitalocean.com:25061
