apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: general
  name: webhook-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: webhook
  namespace: general
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      namespace: general
      labels:
        app: webhook
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: general
      containers:
        - name: webhook
          image: registry.digitalocean.com/athenabot/webhook-service:latest
          ports:
            - containerPort: 3000
