apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: general
  name: calendar-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: calendar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: general
  name: calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      namespace: general
      labels:
        app: calendar
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: general
      containers:
        - name: calendar
          image: registry.digitalocean.com/athenabot/calendar-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: rediss://default:kulqkv6en3um9u09@private-athena-redis-do-user-9223163-0.b.db.ondigitalocean.com:25061
            - name: PG_URL
              value: postgresql://doadmin:rh3rc0vgg1f706kz@private-athenadb-do-user-9223163-0.b.db.ondigitalocean.com:25060/defaultdb
            - name: SPACES_KEY
              value: PO3PKFAEKCQWOJ6MNQR7
            - name: SPACES_SECRET
              value: SEZOdptcZOxXNMCTFqhWq498ji/1bcR9gOQNBmdiurk
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/grpc-backend: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
    linkerd.io/inject: ingress
  name: http-ingress
  namespace: general
spec:
  rules:
    - host: "calendar.athenabot.com"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: calendar-service
                port:
                  number: 8080
    - host: "dashboard.athenabot.com"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: user-dashboard
                port:
                  number: 3000
    - host: "admin.athenabot.com"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: admin-dashboard-backend
                port:
                  number: 3000