apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: monitors
  name: supreme
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: supreme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: monitors
  name: supreme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supreme
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      namespace: monitors
      labels:
        app: supreme
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: monitors
      containers:
        - name: supreme
          image: registry.digitalocean.com/athenabot/monitors/supreme:latest
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: rediss://default:kulqkv6en3um9u09@private-athena-redis-do-user-9223163-0.b.db.ondigitalocean.com:25061
            - name: PG_URL
              value: rediss://default:kulqkv6en3um9u09@athena-redis-do-user-9223163-0.b.db.ondigitalocean.com:25061
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name