apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: antibots
  name: shape
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: shape
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shape
  namespace: antibots
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shape
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      namespace: antibots
      labels:
        app: shape
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: antibots
      containers:
        - name: shape
          image: registry.digitalocean.com/athenabot/antibots/shape:latest
          ports:
            - containerPort: 3000
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: shape-hpa
  namespace: amtibots
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shape
  minReplicas: 5
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50