apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: antibots
  name: ticket
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: ticket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket
  namespace: antibots
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      namespace: antibots
      labels:
        app: ticket
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: antibots
      containers:
        - name: ticket
          image: registry.digitalocean.com/athenabot/antibots/ticket:latest
          ports:
            - containerPort: 3000