apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: antibots
  name: ticket
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: ticket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket
  namespace: antibots
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      namespace: antibots
      labels:
        app: ticket
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: antibots
      containers:
        - name: ticket
          image: registry.digitalocean.com/athenabot/antibots/ticket:latest
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: rediss://default:kulqkv6en3um9u09@private-athena-redis-do-user-9223163-0.b.db.ondigitalocean.com:25061
            - name: PG_URL
              value: postgresql://doadmin:rh3rc0vgg1f706kz@private-athenadb-do-user-9223163-0.b.db.ondigitalocean.com:25060/defaultdb
            #            - name: ENVIRONMENT
            #              value: Production
            - name: SAMPLE_RATE
              value: "1.0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name